services:
  app:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - QDRANT_URL=http://qdrant:6333
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: node server.js
    depends_on:
      - elasticsearch
      - qdrant

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000

  elasticsearch:
    build: ./elasticsearch
    volumes:
      - ./db_data/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - http.cors.allow-headers=X-Requested-With,Content-Type,Content-Length,Authorization
    ports:
      - "9200:9200"

  qdrant:
    image: qdrant/qdrant
    volumes:
      - ./db_data/qdrant:/qdrant/storage
    ports:
      - "6333:6333"

  elasticvue:
    image: cars10/elasticvue
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch


